---
- name: Install apache server   
  hosts: all     
  become: yes
  tasks:
    - name: install apache server 
      yum:
        name: httpd
        state: latest
        update_cache: yes
    - name: Copy file with owner and permissions
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
        owner: ec2-user
        group: ec2-user
        mode: '0644'
    - name: start and enable autostart of apache server
      systemd:
        name: httpd
        state: started
        enabled: yes